[Hero]
[[Hero.list]]
id = 1
name = "Mage"
hp = 150
attack = 30
defence = 1
aptitude = 3.3

[[Hero.list]]
id = 2
name = "Warlock"
hp = 200
attack = 20
defence = 2
aptitude = 2.2

[[Hero.list]]
id = 3
name = "Warrior"
hp = 300
attack = 25
defence = 3
aptitude = 2.75

